questions = {
    "math": [
        {"id": 1, "question": "What is 2 + 2?", "options": ["3", "4", "5", "6"], "correct_answer": "4"},
        {"id": 2, "question": "What is 5 * 5?", "options": ["20", "25", "30", "35"], "correct_answer": "25"},
        {"id": 3, "question": "What is 7 - 3?", "options": ["2", "4", "6", "8"], "correct_answer": "4"},
        {"id": 4, "question": "What is 10 / 2?", "options": ["2", "3", "4", "5"], "correct_answer": "5"},
        {"id": 5, "question": "What is the square root of 16?", "options": ["2", "4", "6", "8"], "correct_answer": "4"},
        {"id": 6, "question": "What is 3 squared?", "options": ["6", "9", "12", "15"], "correct_answer": "9"},
        {"id": 7, "question": "What is the value of pi (π) to two decimal places?", "options": ["3.14", "3.141", "3.142", "3.143"], "correct_answer": "3.14"},
        {"id": 8, "question": "What is the next number in the sequence: 1, 3, 5, 7, ...?", "options": ["9", "10", "11", "12"], "correct_answer": "9"},
        {"id": 9, "question": "What is the perimeter of a square with side length 4 units?", "options": ["12", "16", "20", "24"], "correct_answer": "16"},
        {"id": 10, "question": "What is the area of a triangle with base 6 units and height 8 units?", "options": ["24", "30", "36", "42"], "correct_answer": "24"},
        {"id": 11, "question": "What is the circumference of a circle with radius 5 units?", "options": ["10π", "15π", "20π", "25π"], "correct_answer": "10π"},
        {"id": 12, "question": "What is 2 to the power of 4?", "options": ["8", "12", "16", "20"], "correct_answer": "16"},
        {"id": 13, "question": "What is the next prime number after 17?", "options": ["19", "21", "23", "25"], "correct_answer": "19"},
        {"id": 14, "question": "What is the sum of the first 10 positive integers?", "options": ["45", "50", "55", "60"], "correct_answer": "55"},
        {"id": 15, "question": "What is the median of the set: {3, 5, 7, 9, 11}?", "options": ["5", "7", "9", "11"], "correct_answer": "7"},
        {"id": 16, "question": "What is the product of the first 5 prime numbers?", "options": ["120", "130", "140", "150"], "correct_answer": "2310"},
        {"id": 17, "question": "What is the value of log10(100)?", "options": ["1", "2", "3", "4"], "correct_answer": "2"},
        {"id": 18, "question": "What is the greatest common divisor of 24 and 36?", "options": ["6", "8", "10", "12"], "correct_answer": "12"},
        {"id": 19, "question": "What is the area of a circle with diameter 10 units?", "options": ["25π", "50π", "75π", "100π"], "correct_answer": "25π"},
        {"id": 20, "question": "What is the value of sin(90°)?", "options": ["0", "1", "-1", "2"], "correct_answer": "1"}
    ],
    "science": [
        {"id": 1, "question": "What is the chemical symbol for water?", "options": ["H2O", "CO2", "O2", "CH4"], "correct_answer": "H2O"},
        {"id": 2, "question": "What is the freezing point of water?", "options": ["0°C", "100°C", "-273°C", "25°C"], "correct_answer": "0°C"},
        {"id": 3, "question": "What is the atomic number of carbon?", "options": ["6", "7", "8", "9"], "correct_answer": "6"},
        {"id": 4, "question": "What is the boiling point of water in Fahrenheit?", "options": ["212°F", "250°F", "300°F", "350°F"], "correct_answer": "212°F"},
        {"id": 5, "question": "What is the chemical formula for table salt?", "options": ["NaCl", "KCl", "HCl", "CaCl2"], "correct_answer": "NaCl"},
        {"id": 6, "question": "What is the largest planet in our solar system?", "options": ["Jupiter", "Saturn", "Uranus", "Neptune"], "correct_answer": "Jupiter"},
        {"id": 7, "question": "What is the speed of light in a vacuum?", "options": ["299,792,458 m/s", "300,000,000 m/s", "310,000,000 m/s", "320,000,000 m/s"], "correct_answer": "299,792,458 m/s"},
        {"id": 8, "question": "What is the process by which plants make their own food?", "options": ["Photosynthesis", "Respiration", "Digestion", "Transpiration"], "correct_answer": "Photosynthesis"},
        {"id": 9, "question": "What is the Earth's primary source of energy?", "options": ["Sun", "Moon", "Stars", "Planets"], "correct_answer": "Sun"},
        {"id": 10, "question": "What is the chemical symbol for oxygen?", "options": ["O2", "CO2", "H2O", "N2"], "correct_answer": "O2"},
        {"id": 11, "question": "What is the study of matter and its motion called?", "options": ["Physics", "Chemistry", "Biology", "Geology"], "correct_answer": "Physics"},
        {"id": 12, "question": "What is the chemical symbol for gold?", "options": ["Au", "Ag", "Cu", "Fe"], "correct_answer": "Au"},
        {"id": 13, "question": "What is the main component of Earth's atmosphere?", "options": ["Nitrogen", "Oxygen", "Carbon dioxide", "Argon"], "correct_answer": "Nitrogen"},
        {"id": 14, "question": "What is the process of a liquid turning into a gas at the surface of the liquid?", "options": ["Evaporation", "Condensation", "Sublimation", "Freezing"], "correct_answer": "Evaporation"},
        {"id": 15, "question": "What is the chemical symbol for sodium?", "options": ["Na", "S", "Ca", "Mg"], "correct_answer": "Na"},
        {"id": 16, "question": "What is the study of the Earth's crust called?", "options": ["Geology", "Biology", "Chemistry", "Physics"], "correct_answer": "Geology"},
        {"id": 17, "question": "What is the hardest natural substance on Earth?", "options": ["Diamond", "Graphite", "Quartz", "Topaz"], "correct_answer": "Diamond"},
        {"id": 18, "question": "What is the process of plants releasing water vapor into the air?", "options": ["Transpiration", "Photosynthesis", "Condensation", "Evaporation"], "correct_answer": "Transpiration"},
        {"id": 19, "question": "What is the chemical symbol for carbon dioxide?", "options": ["CO2", "CO", "O2", "H2O"], "correct_answer": "CO2"},
        {"id": 20, "question": "What is the study of the universe beyond the Earth's atmosphere called?", "options": ["Astronomy", "Astrophysics", "Cosmology", "Meteorology"], "correct_answer": "Astronomy"}
    ],
    "history": [
        {"id": 1, "question": "Who was the first President of the United States?", "options": ["George Washington", "Thomas Jefferson", "Abraham Lincoln", "John Adams"], "correct_answer": "George Washington"},
        {"id": 2, "question": "In what year did World War II end?", "options": ["1941", "1943", "1945", "1947"], "correct_answer": "1945"},
        {"id": 3, "question": "Who wrote the Declaration of Independence?", "options": ["Thomas Jefferson", "George Washington", "Benjamin Franklin", "John Adams"], "correct_answer": "Thomas Jefferson"},
        {"id": 4, "question": "Who was the first female Prime Minister of the United Kingdom?", "options": ["Margaret Thatcher", "Theresa May", "Queen Elizabeth II", "Indira Gandhi"], "correct_answer": "Margaret Thatcher"},
        {"id": 5, "question": "What ancient civilization built the pyramids?", "options": ["Egyptians", "Greeks", "Romans", "Persians"], "correct_answer": "Egyptians"},
        {"id": 6, "question": "Who was the first Emperor of Rome?", "options": ["Julius Caesar", "Augustus", "Nero", "Trajan"], "correct_answer": "Augustus"},
        {"id": 7, "question": "What year did Christopher Columbus discover America?", "options": ["1492", "1498", "1501", "1505"], "correct_answer": "1492"},
        {"id": 8, "question": "Who was the longest-reigning British monarch?", "options": ["Queen Victoria", "Queen Elizabeth II", "King George III", "Queen Elizabeth I"], "correct_answer": "Queen Victoria"},
        {"id": 9, "question": "What was the name of the ship that brought the Pilgrims to America in 1620?", "options": ["Mayflower", "Santa Maria", "Nina", "Pinta"], "correct_answer": "Mayflower"},
        {"id": 10, "question": "Who was the first African-American President of the United States?", "options": ["Barack Obama", "Bill Clinton", "George W. Bush", "Donald Trump"], "correct_answer": "Barack Obama"},
        {"id": 11, "question": "Who wrote 'The Art of War'?", "options": ["Sun Tzu", "Machiavelli", "Julius Caesar", "Alexander the Great"], "correct_answer": "Sun Tzu"},
        {"id": 12, "question": "What was the capital of the Byzantine Empire?", "options": ["Constantinople", "Rome", "Athens", "Jerusalem"], "correct_answer": "Constantinople"},
        {"id": 13, "question": "Who was the first woman to win a Nobel Prize?", "options": ["Marie Curie", "Rosalind Franklin", "Ada Lovelace", "Jane Goodall"], "correct_answer": "Marie Curie"},
        {"id": 14, "question": "What year did the American Civil War end?", "options": ["1865", "1870", "1875", "1880"], "correct_answer": "1865"},
        {"id": 15, "question": "Who was the first European explorer to reach India by sea?", "options": ["Vasco da Gama", "Christopher Columbus", "Ferdinand Magellan", "Marco Polo"], "correct_answer": "Vasco da Gama"},
        {"id": 16, "question": "What was the name of the ship that sank in 1912 after hitting an iceberg?", "options": ["Titanic", "Lusitania", "Queen Mary", "Bismarck"], "correct_answer": "Titanic"},
        {"id": 17, "question": "What year did the French Revolution begin?", "options": ["1789", "1793", "1798", "1801"], "correct_answer": "1789"},
        {"id": 18, "question": "Who was the first woman to fly solo across the Atlantic Ocean?", "options": ["Amelia Earhart", "Bessie Coleman", "Harriet Quimby", "Jacqueline Cochran"], "correct_answer": "Amelia Earhart"},
        {"id": 19, "question": "What was the name of the ship that carried the Spanish Armada?", "options": ["San Salvador", "Santa Maria", "San Felipe", "San Juan"], "correct_answer": "San Salvador"},
        {"id": 20, "question": "Who was the first person to circumnavigate the globe?", "options": ["Ferdinand Magellan", "Sir Francis Drake", "James Cook", "Christopher Columbus"], "correct_answer": "Ferdinand Magellan"}
    ]
}
